plugins/platform-core-1.0.0/grails-app/controllers/org/grails/plugin/platform/controllers/PlatformToolsController.groovy
/* Copyright 2011-2013 the original author or authors:
 *
 *    Marc Palmer (marc@grailsrocks.com)
 *    Stéphane Maldini (smaldini@vmware.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.grails.plugin.platform.controllers

class PlatformToolsController {

    def grailsSecurity
    def grailsNavigation
    def grailsEvents
    def grailsUiExtensions

    def index = {
    }

    def security = {
        [identity:grailsSecurity.userIdentity, info:grailsSecurity.userInfo]
    }

    def showPluginConfig = {
        [allPluginConfig:grailsApplication.config.plugin.flatten()]
    }

    def showNavigation = {
        [
            navScopes:grailsNavigation.scopes,
            navNodesById:grailsNavigation.nodesById,
            navNodesByControllerAction:grailsNavigation.nodesByControllerAction
        ]
    }

    def showEvents = {
        [events:grailsEvents.eventDefinitions]
    }

    def showUiExtensions = {
        pluginSession.testKey = 'session testing'
        pluginRequestAttributes.testKey = 'request attribute testing'
        pluginFlash.testKey = 'flash testing, only see this on second load!'

        displayMessage text:"This is an alert message", type:'alert'

        [
            pluginSessionInfo: grailsUiExtensions.getPluginSession('platformCore').toMap(),
            pluginFlashInfo: grailsUiExtensions.getPluginFlash('platformCore').toMap(),
            pluginRequestInfo: grailsUiExtensions.getPluginRequestAttributes('platformCore').toMap(),
        ]
    }

/*
    def jsmodel = {
        [book:[title:'Test book title', author:'Test Author']]
    }
*/
}

plugins/platform-core-1.0.0/grails-app/views/layouts/platform/dev.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <g:layoutHead/>
    <plugin:isAvailable name="resources">
        <r:require module="plugin.platformCore.tools"/>
        <r:layoutResources/>
    </plugin:isAvailable>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <g:link class="brand" controller="platformTools">Grails Platform Core</g:link>
                <nav:primary class="nav" scope="dev"/>
            </div>
        </div>
    </div>

    <div class="container">
        <g:layoutBody/>
    </div>

    <plugin:isAvailable name="resources">
        <r:layoutResources/>
    </plugin:isAvailable>
</body>
</html>

plugins/platform-core-1.0.0/grails-app/views/layouts/platform/overlay.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <g:layoutHead/>
    <plugin:isAvailable name="resources">
        <r:layoutResources/>
    </plugin:isAvailable>
</head>
<body>
    <g:layoutBody/>

    <plugin:isAvailable name="resources">
        <r:layoutResources/>
    </plugin:isAvailable>
</body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/_uiOverlay.gsp
${bodyContent()}

plugins/platform-core-1.0.0/grails-app/views/platformTools/index.gsp
<!doctype html>
<html>
	<head>
		<title>Plugin Platform</title>
        <meta name="layout" content="platform/dev"/>
	</head>
	<body>
        <div class="row>">
            <div class="span12">
                <div class="hero-unit">
                    <h1>Grails Plugin Platform</h1>

                    <p>Welcome the the Grails Plugin Platform test page. Here's what you can do:

                    <ul>
                        <li><g:link controller="platformTools" action="security">Security information</g:link></li>
                        <li><g:link controller="platformTools" action="showPluginConfig">Plugin Configuration</g:link></li>
                        <li><g:link controller="platformTools" action="showNavigation">Navigation</g:link></li>
                        <li><g:link controller="platformTools" action="showEvents">Events</g:link></li>
                        <li><g:link controller="platformTools" action="showUiExtensions">UI Extensions</g:link></li>
            <%-- <li><g:link controller="platformTools" action="jsmodel" params="[id:5150, max:50, offset:0]">See the JSON model test</g:link></li>
            --%>
                    </ul>
                    </p>
                </div>
            </div>
        </div>

	</body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/jsmodel.gsp
<html>
    <head>
        <title>JS Model</title>
        <meta name="layout" content="platform/dev"/>
        <g:set var="output">
            <ui:jsModel model="book" i18n="test.ui.title,test.ui.other.title" params="*"/>
        </g:set>
        ${output}
    </head>
    <body>
        <h1>JS Model Test</h1>

        <p>This has been written to head:
        <pre>
            ${output.encodeAsHTML()}
        </pre>
        </p>
    </body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/security.gsp
<html>
    <head>
        <title>Security</title>
        <meta name="layout" content="platform/dev"/>
    </head>
    <body>
        <h1>Security</h1>

        <g:if test="${grailsApplication.mainContext.grailsSecurityBridge}">
            <p>The security provider is: ${grailsApplication.mainContext.grailsSecurityBridge?.getClass()}.</p>
        </g:if>
        <g:else>
            <p>There's no security provider installed. You need to install a plugin that has one or declare a bean called grailsSecurityBridge that
                implements the <code>SecurityBridge</code> interface. See the documentation for details</p>
        </g:else>

        <p>The current user is: <s:identity/>.</p>

        <s:ifPermitted role="ADMIN">
            <p>The current user is an ADMIN</p>
        </s:ifPermitted>
        <s:ifNotPermitted role="ADMIN">
            <p>The current user is not an ADMIN</p>
        </s:ifNotPermitted>

        <p>The info from the security implementation is:
            <pre>
                <s:info/>
            </pre>
        </p>

        <g:if test="${grailsApplication.mainContext.grailsSecurityBridge}">
            <p>Log in button: <s:loginButton/>, log out button <s:logoutButton/> and sign up button <s:signupButton/>
            </p>
        </g:if>
        <g:else>
            <p>If you had a security provider installed, you would see the default log in/out/signup buttons here.</p>
        </g:else>
    </body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/showEvents.gsp
<html>
    <head>
        <title>Events</title>
        <meta name="layout" content="platform/dev"/>
    </head>
    <body>
        <h1>Events</h1>

        <p>The following events are registered:</p>
        <ul>
        <g:each in="${events}" var="eventDef">
            <li>${eventDef.topic} in namespace ${eventDef.namespace} with attributes ${eventDef.othersAttributes}</li>
        </g:each>
        </ul>
    </body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/showNavigation.gsp
<html>
    <head>
        <title>Navigation</title>
        <meta name="layout" content="platform/dev"/>
        <style>
        .usernav { float: right; }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="span12">
                <div class="usernav">
                    <p>This is our user navigation</p>
                    <nav:menu scope="user"/>
                </div>

                <h1>Navigation</h1>

                <p>The current active path is "${nav.activePath().encodeAsHTML()}", which means the active node is ${nav.activeNode()?.id.encodeAsHTML()}</p>

                <h2>Test navigation for the active path</h2>
                <g:form mapping="platformNormal" action="showNavigation">
                    <input type="text" name="activePath" value="${params.activePath}" size="80"/>
                    <input type="submit"/>
                </g:form>

                <p>First active node for the path [${params.activePath}] is: ${nav.firstActiveNode(path:params.activePath)?.id}</p>
                <p>Primary navigation for this path:</p>
                <nav:primary scope="${nav.scopeForActivationPath(path:params.activePath)}" path="${params.activePath}"/>

                <p>Secondary navigation for this path:</p>
                <nav:secondary path="${params.activePath}"/>

                <p>Two-deep menu for this path:</p>
                <nav:menu scope="${params.activePath}" path="${params.activePath}" class="" depth="2"/>

                <p>Two-deep menu for this path with custom render:</p>
                <nav:menu scope="${params.activePath}" path="${params.activePath}" class="" custom="true" depth="2">
                    Item: <p:callTag tag="p:smartLink" attrs="${linkArgs}"/>
                </nav:menu>

                <h2>Available navigation scopes</h2>
                <ul>
                <g:each in="${navScopes}" var="scope">
                    <li>${scope.name.encodeAsHTML()}
                    <nav:items scope="${scope}" var="item">
                        id: ${item.id.encodeAsHTML()}
                            <g:if test="${item.id == params.activePath}"><strong>ACTIVE</strong></g:if>
                            <br/>
                            name: ${item.name.encodeAsHTML()}<br/>
                            order: ${item.order.encodeAsHTML()}<br/>
                            link args: ${item.linkArgs.encodeAsHTML()} (<p:callTag tag="g:link" attrs="${new HashMap(item.linkArgs)}">Test</p:callTag>)<br/>
                            action aliases: ${item.actionAliases?.encodeAsHTML()}<br/>
                            title: ${item.titleMessageCode.encodeAsHTML()} (<g:message code="${item.titleMessageCode}" encodeAs="HTML"/>)<br/>
                            default title: ${item.titleDefault.encodeAsHTML()}<br/>
                            data: ${item.data.encodeAsHTML()}<br/>
                            visible: ${item.visibleClosure ? 'from Closure' : item.visible}<br/>
                            enabled: ${item.enabledClosure ? 'from Closure' : item.enabled}<br/>
                    </nav:items>
                    </li>
                </g:each>
                </ul>

                <h2>Nodes by id cache</h2>
                <ul>
                <g:each in="${navNodesById}" var="n">
                    <li>${n.key.encodeAsHTML()} &raquo; ${n.value.name.encodeAsHTML()} <g:if test="${n.value instanceof org.grails.plugin.platform.navigation.NavigationItem}"> (${n.value.linkArgs.encodeAsHTML()})</g:if></li>
                </g:each>
                </ul>

                <h2>Nodes by controller/action</h2>
                <ul>
                <g:each in="${navNodesByControllerAction}" var="n">
                    <li>${n.key.encodeAsHTML()} &raquo; ${n.value.name.encodeAsHTML()} (${n.value.linkArgs.encodeAsHTML()})</li>
                </g:each>
                </ul>

                <footer>
                    <p>This is our footer navigation</p>
                    <nav:menu scope="footer"/>
                </footer>
            </div>
        </div>
    </body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/showPluginConfig.gsp
<html>
    <head>
        <title>Plugin Config</title>
        <meta name="layout" content="platform/dev"/>
    </head>
    <body>
        <div class="row">
            <div class="span12">
                <div class="page-heading">
                    <h1>Plugin Config</h1>
               </div>

                <p>All plugin config:
                    <pre>
                        <p:prettyPrint value="${allPluginConfig}"/>
                    </pre>
                </p>

            </div>
        </div>
    </body>
</html>

plugins/platform-core-1.0.0/grails-app/views/platformTools/showUiExtensions.gsp
<html>
    <head>
        <title>UI Extensions</title>
        <meta name="layout" content="platform/dev"/>
    </head>
    <body>
        <div class="row>">
            <div class="span12">
                <h1>UI Extensions</h1>

                <h2>Display messages</h2>
                <p>The controller message was:</p>
                <p:tagDemo tag="p:displayMessage"/>

                <h2>Buttons</h2>
                <p:tagDemo tag="p:button">Click me I'm a button</p:tagDemo>
                <p:tagDemo tag="p:button" kind="anchor">Click me I'm a link</p:tagDemo>
                <p:tagDemo tag="p:button" kind="submit" action="update">Click me I'm a submit</p:tagDemo>
                <p:tagDemo tag="p:button" kind="button" text="text.from.i18n" textScope="my.i18n.scope">Click me I'm a button</p:tagDemo>
                <p:tagDemo tag="p:button" kind="submit" action="update" text="text.from.i18n" textPlugin="emailConfirmation">Click me I'm a submit</p:tagDemo>
                <p:tagDemo tag="p:button" kind="button" text="text.from.i18n" textScope="my.i18n.scope"/>
                <p:tagDemo tag="p:button" kind="submit" action="update" text="text.from.i18n" textPlugin="emailConfirmation"/>

                <h2>Labels</h2>
                <g:form>
                    <p:tagDemo tag="p:label" class="form-data" for="field0" text="this.is.field.zero">With default text</p:tagDemo>
                    <p:tagDemo tag="p:label" class="form-data" for="field1" text="this.is.a.field"/>
                    <p:tagDemo tag="p:label" class="form-data" for="field2" text="this.is.another.field" textScope="my.i18n.scope"/>
                    <p:tagDemo tag="p:label" class="form-data" for="field3" text="this.is.yet.another.field" textPlugin="emailConfirmation"/>
                </g:form>

                <h2>Smart Links</h2>
                <p:tagDemo tag="p:smartLink" controller="platformTools"/>
                <p:tagDemo tag="p:smartLink" controller="platformTools">With default link text</p:tagDemo>
                <p:tagDemo tag="p:smartLink" controller="platformTools" action="showNavigation"/>
                <p:tagDemo tag="p:smartLink" action="showPluginConfig"/>
                <p:tagDemo tag="p:smartLink" action="showPluginConfig" textScope="my.i18n.scope"/>
                <p:tagDemo tag="p:smartLink" action="showPluginConfig" textPlugin="emailConfirmation"/>

                <h2>Branding</h2>
                <p:tagDemo tag="p:organization"/>
                <p:tagDemo tag="p:siteName"/>
                <p:tagDemo tag="p:siteURL"/>
                <p:tagDemo tag="p:siteLink"/>
                <p:tagDemo tag="p:year"/>

                <h2>Namespaced session, flash and request attributes</h2>
                <p>Session: <p:prettyPrint value="${pluginSessionInfo}"/></p>
                <p>Flash: <p:prettyPrint value="${pluginFlashInfo}"/></p>
                <p>Request: <p:prettyPrint value="${pluginRequestInfo}"/></p>

                <h2>Namespaced i18n messages</h2>
                <p>There is a <code>p:text</code> tag that is like <code>g:message</code> but uses plugin namespaced i18n codes
                    and uses the body as default text. The messages are namespaced as <code>plugin.[GSP plugin Name].[code]</code>:
                    <blockquote>
                        <p:tagDemo tag="p:text" code="test.message">This will not show</p:tagDemo>
                    </blockquote>
                    <blockquote>
                        <p:tagDemo tag="p:text" code="test.missing.message">This will show because the code used does not exist</p:tagDemo>
                    </blockquote>
                </p>
                <p>Also supports multiple codes, resolving until it finds a match
                    <blockquote>
                        <p:tagDemo tag="p:text" codes="['nonsense.message', 'test.message']">This will not show</p:tagDemo>
                    </blockquote>
                </p>
            </div>
        </div>
    </body>
</html>